RUN
{
Change archivelog all validate;
ALLOCATE CHANNEL DISK_NMD_ARCHIVELOG_1 TYPE DISK;
BACKUP ARCHIVELOG ALL DELETE INPUT FORMAT '/oracle/RMAN_BACKUP/BACKUP/ORA/DEVQA/NMD/INCR/NMD_ARCH_%s_%p_%t' TAG=ARCHIVE_LOG;
RELEASE CHANNEL DISK_NMD_ARCHIVELOG_1;

ALLOCATE CHANNEL DISK_NMD_DATAFILE_1 TYPE DISK;
BACKUP incremental level 1 FILESPERSET 5 DATABASE FORMAT '/oracle/RMAN_BACKUP/BACKUP/ORA/DEVQA/NMD/INCR/NMD_DATAFILE_%s_%p_%t' TAG=DAILY_INCR;
sql 'alter system archive log current';
RELEASE CHANNEL DISK_NMD_DATAFILE_1;

Change archivelog all validate;
ALLOCATE CHANNEL DISK_NMD_ARCHIVELOG_1 TYPE DISK;
BACKUP ARCHIVELOG ALL DELETE INPUT FORMAT '/oracle/RMAN_BACKUP/BACKUP/ORA/DEVQA/NMD/INCR/NMD_ARCH_%s_%p_%t' TAG=ARCHIVE_LOG;
RELEASE CHANNEL DISK_NMD_ARCHIVELOG_1;

ALLOCATE CHANNEL DISK_NMD_CURRENT_CONTROLFILE_1 TYPE DISK;
BACKUP CURRENT CONTROLFILE FORMAT '/oracle/RMAN_BACKUP/BACKUP/ORA/DEVQA/NMD/INCR/NMD_CNTRL_%s_%p_%t'
TAG=CURRENT_CONTROLFILE;
RELEASE CHANNEL DISK_NMD_CURRENT_CONTROLFILE_1;

ALLOCATE CHANNEL DISK_NMD_COPY_CURRENT_CONTROLFILE_1 TYPE DISK;
COPY CURRENT CONTROLFILE TO '/oracle/RMAN_BACKUP/BACKUP/ORA/DEVQA/NMD/INCR/control01.CTL';
RELEASE CHANNEL DISK_NMD_COPY_CURRENT_CONTROLFILE_1;

ALLOCATE CHANNEL DISK_SPFILE TYPE DISK;
BACKUP SPFILE FORMAT '/oracle/RMAN_BACKUP/BACKUP/ORA/DEVQA/NMD/INCR/spfileNMD.ora';
RELEASE CHANNEL DISK_SPFILE;
}

